name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      nix_prefix: nix shell -i -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/33d1e753c82ffc557b4a585c77de43d4c922ebb5.tar.gz nixpkgs#coreutils nixpkgs#gcc nixpkgs#musl.dev nixpkgs#rustup nixpkgs#cargo nixpkgs#llvmPackages_18.libllvm.dev nixpkgs\#llvmPackages_18.clang -c
    steps:
    - uses: actions/checkout@v4
      
    - name: print architecture
      run: uname -p
    - name: save arch
      run: echo "RUNNERCPUARCH=$(uname -p -p)" >> $GITHUB_ENV
    - name: test arch
      run: echo "${{ env.RUNNERCPUARCH }}"
    
    - name: Use the determinate nix installer
      uses: DeterminateSystems/nix-installer-action@main

    - name: Print nix version
      run: nix --version
      
    - name: Download musl target
      run: ${{env.nix_prefix}} rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: ${{env.nix_prefix}} cargo build --target=x86_64-unknown-linux-musl --release --verbose
    - name: Run tests
      run: ${{env.nix_prefix}} cargo test --release --verbose
      
    - name: Nightly Release (Linux)
      uses: andelf/nightly-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "nightly-linux-${{ env.RUNNERCPUARCH }}"
        name: "Linux Nightly ${{ env.RUNNERCPUARCH }}"
        files: "target/release/konoran*"
    
