name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      nix_prefix: nix shell -i -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/33d1e753c82ffc557b4a585c77de43d4c922ebb5.tar.gz nixpkgs#coreutils nixpkgs#cargo nixpkgs#llvmPackages_18.libllvm.dev nixpkgs\#llvmPackages_18.clang -c
    steps:
    - uses: actions/checkout@v4
      
    - name: print architecture
      run: uname -p
    - name: save arch
      run: echo "RUNNERCPUARCH=$(uname -p -p)" >> $GITHUB_ENV
    - name: test arch
      run: echo "${{ env.RUNNERCPUARCH }}"
      
    - name: Use the determinate nix installer
      uses: DeterminateSystems/nix-installer-action@main
      with:
        source-revision: 7011c077ec491da410fbc39f68676b0908b9ce7e
      
    - name: Build
      run: ${{env.nix_prefix}} env RUSTFLAGS='-C target-feature=+crt-static' cargo build --target x86_64-unknown-linux-gnu --release --verbose
    - name: Run tests
      run: ${{env.nix_prefix}} env RUSTFLAGS='-C target-feature=+crt-static' cargo test --target x86_64-unknown-linux-gnu --release --verbose
      
    - name: Nightly Release (Linux)
      uses: andelf/nightly-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "nightly-linux-${{ env.RUNNERCPUARCH }}"
        name: "Linux Nightly ${{ env.RUNNERCPUARCH }}"
        files: "target/release/konoran*"
    
