name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      
    - name: print architecture
      run: uname -p
    - name: save arch
      run: echo "RUNNERCPUARCH=$(uname -p -p)" >> $GITHUB_ENV
    - name: test arch
      run: echo "${{ env.RUNNERCPUARCH }}"
      
    - name: Use the determinate nix installer
      uses: DeterminateSystems/nix-installer-action@main
      with:
        source-revision: 7011c077ec491da410fbc39f68676b0908b9ce7e
      
    - name: set up cachix
      run: nix-env -iA cachix -f https://cachix.org/api/v1/install

    - name: use dependency cache
      run: cachix use konoran-cache

    - name: Build
      run: nix build -L
      
    - name: Inspect
      run: ls result/bin/
      
    - name: Nightly Release (Linux)
      uses: andelf/nightly-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "nightly-linux-${{ env.RUNNERCPUARCH }}"
        name: "Linux Nightly ${{ env.RUNNERCPUARCH }}"
        body: "Statically built release for 64-bit Linux systems. Does not support JIT mode, but does support outputting object, asm, and llvm ir files."
        files: "result/bin/konoran*"
    
