name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      nix_prefix: nix shell -i -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/33d1e753c82ffc557b4a585c77de43d4c922ebb5.tar.gz nixpkgs#coreutils nixpkgs#cargo nixpkgs#llvmPackages_18.libllvm.dev nixpkgs\#llvmPackages_18.clang -c
    steps:
    - uses: actions/checkout@v4
      
    - name: Use the determinate nix installer
      uses: DeterminateSystems/nix-installer-action@main
      
    - name: print architecture
      run: uname -a
    
    - name: Build
      run: ${{env.nix_prefix}} cargo build --release --verbose
    - name: Run tests
      run: ${{env.nix_prefix}} cargo test --release --verbose
