name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: release-downloader
      uses: robinraju/release-downloader@v1.10
      with:
        repository: wareya/llvm-custom-builds
        # The github tag to download the release from
        tag: "18.x"
        fileName: "llvm-linux-amd64.tar.xz"
        out-file-path: "llvm"
        
    - name: print architecture
      run: uname -a
    
    - name: unarchive llvm
      run: cd llvm && tar xf llvm-linux-amd64.tar.xz && ls . && cd ../
      
    - name: Build
      run: LLVM_SYS_180_PREFIX=llvm/ cargo build --verbose
    - name: Run tests
      run: LLVM_SYS_180_PREFIX=llvm/ cargo test --verbose
